### ISSUE TITLE
Assertion triggered on Catalina

### ISSUE THREAD

**Issue by blochberger** [0xbf00/simbple#2]
https://github.com/0xbf00/simbple/blob/32b33b3b9c6ee77e2a71dcc433ad60d4c64b7162/src/sb/actions.c#L93

The assertion is triggered for *Safari* and *iMovie*:

```sh
simbple --scheme ~/Library/Containers/com.apple.Safari/Container.plist
simbple --scheme ~/Library/Containers/com.apple.iMovieApp/Container.plist
```

**Comment by 0xbf00** [comment]
Commit 45358c79a7cce08a56f72d30868c0db9f2247a18 fixes the problem for `Safari.app`. Please test whether the fix also applies to `iMovie.app`.

**Comment by blochberger** [comment]
I can confirm that it works with `Safari.app` as well as with `iMovie.app`. Thanks!
