### ISSUE TITLE
Default CMake/Make process does not build properly on macOS BigSur

### ISSUE THREAD

**Issue by Instructor123** [0xbf00/simbple#6]
I'm running macOS Big Sur Version 11.6 on a 2019 MacBook Pro Intel Core i5.

I've followed the steps in the README to install the pre-requisites through brew, but when I issue the "make" command I receive the below error:
```
[  2%] Building CXX object dependencies/sbpldump/CMakeFiles/sbpldump.dir/convert.cpp.o
/Users/<redacted>/git/simbple/src/dependencies/sbpldump/convert.cpp:11:10: fatal error: 'nlohmann/json.hpp' file not found
#include <nlohmann/json.hpp>
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [dependencies/sbpldump/CMakeFiles/sbpldump.dir/convert.cpp.o] Error 1
make[1]: *** [dependencies/sbpldump/CMakeFiles/sbpldump.dir/all] Error 2
make: *** [all] Error 2
```
I have to update the CMakeLists.txt (simbple/src/CMakeLists.txt) with the instructions below in order to get the program to compile:
```
add_compile_options(-I/usr/local/opt/nlohmann_json/include)

add_compile_options(-I/usr/local/opt/argp-standalone/include)
add_link_options(-L/usr/local/opt/argp-standalone/lib)
```

I do not believe this should be default behavior, is there something I'm missing in the installation or setup phase?

Thanks for any and all advice!

**Comment by 0xbf00** [comment]
Thanks for the report! I've tried to reproduce your issue today but unfortunately had no luck. I used a fresh macOS 11.6 installation and the instructions worked out of the box there. The only software installed on the machine was:

* Xcode Command Line Tools
* homebrew
* cmake, nlohmann-json and argp-standalone as per the instructions

Building completed without the error you encountered. Is it possible your specific machine is configured in a certain non-standard way, which might result in the problems you've encountered?

Please note that while I'm happy to debug this issue with you, `simbple` has not been tested on Big Sur. It might work or it might not, and I unfortunately don't have the time right now to actively work on it. Happy to take pull requests though!

**Comment by Instructor123** [comment]
Interesting. I'll look into it more and see if I can find something that's making things act strangely.

I do however get it to build, but it complains that I'm not running on one of the supported operating systems. Which isn't surprising as it only lists sierra and high_sierra as supported platforms.

**Comment by 0xbf00** [comment]
You should still be able to select one of the supported platforms and the tool should still be able to generate the sandbox profile for that platform, but yes, at the moment, there is no support for Big Sur.

The current architecture requires some manual effort to add support for new macOS releases. If you’d like to add support, have a look at the `src/platform_data` subfolder and the `ida_scripts` subfolder. These should give you an idea of what’s necessary to change (assuming the sandbox implementation on Big Sur is mostly unchanged)

Ideally, `simbple` could parse the system’s libraries to extract the data structures it needs but that has not been implemented.

**Comment by Instructor123** [comment]
Yeah I'm definitely interested in extending it for Big Sur, though it'll probably take a while to get acquainted with the code base and techniques.

Also something must have been updated because when I select high_sierra I get an error.

<img width="1059" alt="simbple_error" src="https://user-images.githubusercontent.com/52050853/136960651-059a7931-e922-4ca1-be22-3c9392394329.png">

**Comment by 0xbf00** [comment]
Sure looks that way. If you manage to get it to work, please feel free to open a PR.

**Comment by Instructor123** [comment]
Will do.  I guess I'll mark this as closed, then create a new issue for Big Sur support.
